# Documentation
# https://docs.docker.com/compose/compose-file

version: '3.7'

services:

  consul-agent: &consul-agent
    image: consul
    container_name: consul-agent
    networks:
      - mss-declan
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-bootstrap:
    <<: *consul-agent
    container_name: consul-server-bootstrap
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"

  rabbitmq:
    image: rabbitmq:3.9-management
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mss-declan

  zipkin:
    image: openzipkin/zipkin:2.23
    restart: always
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672
    networks:
      - mss-declan
    depends_on:
      - rabbitmq

  zuul-server:
    image: zuul-server
    restart: always
    container_name: zuul-server
    ports:
      - "8765:8765"
    networks:
      - mss-declan
    depends_on:
      - consul-server-bootstrap

  auth-server:
    image: auth-service
    restart: always
    container_name: auth-service
    ports:
      - "9999:9999"
    networks:
      - mss-declan
    depends_on:
      - consul-server-bootstrap

  product-service:
    image: product-service
    restart: always
    container_name: product-service
    networks:
      - mss-declan
    depends_on:
      - consul-server-bootstrap

  recommendation-service:
    image: recommendation-service
    restart: always
    container_name: recommendation-service
    networks:
      - mss-declan
    depends_on:
      - consul-server-bootstrap

  review-service:
    image: review-service
    restart: always
    container_name: review-service
    networks:
      - mss-declan
    depends_on:
      - consul-server-bootstrap

  product-composite-service:
    image: product-composite-service
    restart: always
    container_name: product-composite-service
    networks:
      - mss-declan
    depends_on:
      - consul-server-bootstrap

networks:
  mss-declan:
    driver: bridge
