# Documentation
# https://docs.docker.com/compose/compose-file

version: '3.7'

services:

#  consul-agent: &consul-agent
#    image: consul
#    container_name: consul-agent
#    networks:
#      - mss-declan
#    command: "agent -retry-join consul -client 0.0.0.0"
#
#  consul:
#    <<: *consul-agent
#    container_name: consul
#    ports:
#      - "8400:8400"
#      - "8500:8500"
#      - "8600:8600"
#      - "8600:8600/udp"
#    command: "agent -server -bootstrap-expect 1 -ui -client 0.0.0.0"

  consul:
    image: consul
    container_name: consul
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    networks:
      - mss-declan
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO




  rabbitmq:
    image: rabbitmq:3.9-management
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mss-declan

  zipkin:
    image: openzipkin/zipkin:2.23
    restart: always
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672
    networks:
      - mss-declan
    depends_on:
      - rabbitmq

  zuul-server:
    image: zuul-server
    restart: always
    container_name: zuul-server
    ports:
      - "8765:8765"
    networks:
      - mss-declan
    depends_on:
      - consul

  auth-server:
    image: auth-service
    restart: always
    container_name: auth-service
    ports:
      - "9999:9999"
    networks:
      - mss-declan
    depends_on:
      - consul

  product-service:
    image: product-service
    restart: always
    container_name: product-service
    networks:
      - mss-declan
    depends_on:
      - consul

  recommendation-service:
    image: recommendation-service
    restart: always
    container_name: recommendation-service
    networks:
      - mss-declan
    depends_on:
      - consul

  review-service:
    image: review-service
    restart: always
    container_name: review-service
    networks:
      - mss-declan
    depends_on:
      - consul

  product-composite-service:
    image: product-composite-service
    restart: always
    container_name: product-composite-service
    networks:
      - mss-declan
    depends_on:
      - consul

  turbine:
    image: turbine
    restart: always
    container_name: turbine
    ports:
      - "8989:8989"
    networks:
      - mss-declan
    depends_on:
      - consul

  hystrix-dashboard:
    image: hystrix-dashboard
    restart: always
    container_name: hystrix-dashboard
    ports:
      - "7979:7979"
    networks:
      - mss-declan
    depends_on:
      - consul

networks:
  mss-declan:
    driver: bridge
