# Documentation
# https://docs.docker.com/compose/compose-file

version: '3.7'

services:

  consul:
    image: consul
    container_name: consul
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    networks:
      - mss-declan
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  rabbitmq:
    image: rabbitmq:3.9-management
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mss-declan

  zipkin:
    image: openzipkin/zipkin:2.23
    restart: always
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672
    networks:
      - mss-declan
    depends_on:
      - rabbitmq
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"
      
  zuul-server:
    image: zuul-server
    restart: always
    container_name: zuul-server
    ports:
      - "8765:8765"
    networks:
      - mss-declan
    depends_on:
      - consul
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  auth-server:
    image: auth-service
    restart: always
    container_name: auth-service
    ports:
      - "9999:9999"
    networks:
      - mss-declan
    depends_on:
      - consul
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  product-service:
    image: product-service
    restart: always
    container_name: product-service
    networks:
      - mss-declan
    depends_on:
      - consul
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  recommendation-service:
    image: recommendation-service
    restart: always
    container_name: recommendation-service
    networks:
      - mss-declan
    depends_on:
      - consul
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  review-service:
    image: review-service
    restart: always
    container_name: review-service
    networks:
      - mss-declan
    depends_on:
      - consul
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  product-composite-service:
    image: product-composite-service
    restart: always
    container_name: product-composite-service
    networks:
      - mss-declan
    depends_on:
      - consul
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

networks:
  mss-declan:
    driver: bridge
