# Documentation
# https://docs.docker.com/compose/compose-file

version: '3.7'

services:

  rabbitmq:
    image: rabbitmq:3.9-management
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - zipkin-rabitmq_default

  zipkin:
    image: openzipkin/zipkin:2.23
    restart: always
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - RABBIT_ADDRESSES=rabbitmq:5672
    networks:
      - zipkin-rabitmq_default
    depends_on:
      - rabbitmq
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  eureka-server:
    image: eureka-server
    restart: always
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - zipkin-rabitmq_default
    depends_on:
      - rabbitmq
      - zipkin
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"
      
  zuul-server:
    image: zuul-server
    restart: always
    container_name: zuul-server
    ports:
      - "8765:8765"
    networks:
      - zipkin-rabitmq_default
    depends_on:
      - eureka-server
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  auth-server:
    image: auth-service
    restart: always
    container_name: auth-service
    ports:
      - "9999:9999"
    networks:
      - zipkin-rabitmq_default
    depends_on:
      - eureka-server
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  product-service:
    image: product-service
    restart: always
    container_name: product-service
    networks:
      - zipkin-rabitmq_default
    depends_on:
      - eureka-server
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  recommendation-service:
    image: recommendation-service
    restart: always
    container_name: recommendation-service
    networks:
      - zipkin-rabitmq_default
    depends_on:
      - eureka-server
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"


  review-service:
    image: review-service
    restart: always
    container_name: review-service
    networks:
      - zipkin-rabitmq_default
    depends_on:
      - eureka-server
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

  product-composite-service:
    image: product-composite-service
    restart: always
    container_name: product-composite-service
    networks:
      - zipkin-rabitmq_default
    depends_on:
      - eureka-server
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"

networks:
  zipkin-rabitmq_default:
    driver: bridge
